import type { Point } from './geometry'

export type Sport = 'padel_doubles' | 'tennis_singles' | 'tennis_doubles'

export type Team = 'home' | 'away'

export type PlayerRole = 'net' | 'baseline' | 'server' | 'returner'

export interface Player {
  id: string
  label: string
  team: Team
  role?: PlayerRole
}

export interface PlayerPosition {
  playerId: string
  /** court-space coordinates in meters; origin is top-left of the court */
  x: number
  y: number
  /** radians, 0 = facing +x; drives attack cone direction */
  facing?: number
}

export type ShotType = 'drive' | 'lob' | 'volley' | 'smash' | 'drop' | 'serve'
export type ShotSpeed = 'slow' | 'medium' | 'fast'

export interface BallPath {
  points: Point[]
  shotType: ShotType
  speed: ShotSpeed
  byPlayerId?: string
}

export type ZoneType = 'danger' | 'open' | 'covered' | 'pressure'

export interface Zone {
  id: string
  type: ZoneType
  polygon: Point[]
  autoGenerated: boolean
  label?: string
}

export interface BackgroundMedia {
  type: 'video' | 'image' | 'none'
  src?: string
  opacity: number
  offsetX: number
  offsetY: number
  scale: number
}

export interface Step {
  id: string
  order: number
  playerPositions: PlayerPosition[]
  ballPath?: BallPath
  zones: Zone[]
  annotation?: string
  /** duration of the transition leading INTO this step from the previous one */
  durationMs: number
}

export interface Scenario {
  id: string
  title: string
  sport: Sport
  tags: string[]
  players: Player[]
  steps: Step[]
  background?: BackgroundMedia
  createdAt: string
  updatedAt: string
  authorId?: string
  isPublic: boolean
}
